fix : run time

diff --git a/.github/workflows/daily_scrape.yml b/.github/workflows/daily_scrape.yml
--- a/.github/workflows/daily_scrape.yml
+++ b/.github/workflows/daily_scrape.yml
@@ -13,15 +13,17 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
-          python-version: "3.12.0"
+          python-version: "3.x"
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r script/requirements.txt
       - name: Run scrapers
         run: |
-          python script/meetup.py
-          python script/luma.py
+          echo "Running meetup.py..."
+          python script/meetup.py || { echo "meetup.py failed"; cat error_meetup.log; exit 1; }
+          echo "Running luma.py..."
+          python script/luma.py || { echo "luma.py failed"; cat error_luma.log; exit 1; }
       - name: Commit and push if changed
         run: |
           git config --global user.name 'benbasic00769'
