fix : more logs

diff --git a/.github/workflows/daily_scrape.yml b/.github/workflows/daily_scrape.yml
--- a/.github/workflows/daily_scrape.yml
+++ b/.github/workflows/daily_scrape.yml
@@ -13,25 +13,27 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
-          python-version: "3.x"
+          python-version: "3.12.0"
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r script/requirements.txt
-          pip list  # This will show all installed packages
+          pip list
       - name: Run scrapers
         run: |
           echo "Current directory: $(pwd)"
           echo "Content of script directory:"
           ls -l script/
           echo "Running meetup.py..."
-          python -v script/meetup.py || { echo "meetup.py failed"; cat error_meetup.log; exit 1; }
+          python -c "import sys; print(sys.path)"
+          python -v script/meetup.py > meetup_output.log 2>&1 || { echo "meetup.py failed"; cat meetup_output.log; exit 1; }
           echo "Running luma.py..."
-          python -v script/luma.py || { echo "luma.py failed"; cat error_luma.log; exit 1; }
+          python -c "import sys; print(sys.path)"
+          python -v script/luma.py > luma_output.log 2>&1 || { echo "luma.py failed"; cat luma_output.log; exit 1; }
       - name: Commit and push if changed
         run: |
           git config --global user.name 'benbasic00769'
           git config --global user.email 'asamieto965@gmail.com'
           git add *.json
-          git status  # This will show which files have changed
+          git status
           git diff --quiet && git diff --staged --quiet || (git commit -m "Update event data" && git push)
